### ISSUE TITLE
NullPointerException in XMOMStorableStructureCache

### ISSUE THREAD

**Issue by corneliuslippert-gip** [Xyna-Factory/xyna-factory#137]
Sometimes we get NullPointerExceptions traversing XMOMStorables like this:
`java.lang.NullPointerException
 at com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache$StorableStructureInformation.traverse(XMOMStorableStructureCache.java:1358)
 at com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache$StorableStructureInformation.traverse(XMOMStorableStructureCache.java:1351)
 at com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache$StorableStructureInformation.traverse(XMOMStorableStructureCache.java:1358)
 at com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache$StorableStructureInformation.traverse(XMOMStorableStructureCache.java:1331)
 at com.gip.xyna.xnwh.persistence.xmom.XMOMPersistenceManagement$StructureCacheUnregistrator.finish(XMOMPersistenceManagement.java:809)
 at com.gip.xyna.xprc.xfractwfe.base.DeploymentHandling.finishUndeploymentHandler(DeploymentHandling.java:257)
 at com.gip.xyna.xprc.xfractwfe.generation.GenerationBase.finishUndeploymentHandler(GenerationBase.java:3120)
 at com.gip.xyna.xfmg.xfctrl.appmgmt.ApplicationManagementImpl.removeRuntimeApplicationInternally(ApplicationManagementImpl.java:1048)
 at com.gip.xyna.xfmg.xfctrl.appmgmt.ApplicationManagementImpl.removeApplicationVersion(ApplicationManagementImpl.java:922)
 at com.gip.xyna.xmcp.xfcli.impl.RemoveapplicationImpl.execute(RemoveapplicationImpl.java:88)
 at com.gip.xyna.xmcp.xfcli.impl.RemoveapplicationImpl.execute(RemoveapplicationImpl.java:38)
 at com.gip.xyna.xmcp.xfcli.generated.Removeapplication.executeInternally(Removeapplication.java:221)
 at com.gip.xyna.xmcp.xfcli.AXynaCommand.execute(AXynaCommand.java:61)
 at com.gip.xyna.xmcp.xfcli.XynaFactoryCLIConnection.tryGeneratedCommands(XynaFactoryCLIConnection.java:517)
 at com.gip.xyna.xmcp.xfcli.XynaFactoryCLIConnection.execute(XynaFactoryCLIConnection.java:418)
 at com.gip.xyna.xmcp.xfcli.XynaFactoryCLIConnection.execute(XynaFactoryCLIConnection.java:374)
 at com.gip.xyna.xmcp.xfcli.XynaFactoryCLIConnection.run(XynaFactoryCLIConnection.java:332)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:834)
`
or 

`
Caused by java.lang.NullPointerException null. (depth: 1)
    at com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache$StorableStructureInformation.collectHierarchyRecursivly(XMOMStorableStructureCache.java:1642)
    at com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache$StorableStructureInformation.generateMergedClone(XMOMStorableStructureCache.java:1584)
    at com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache$XMOMStorableStructureInformation.generateMergedClone(XMOMStorableStructureCache.java:1948)
    at com.gip.xyna.xnwh.persistence.xmom.XMOMPersistenceOperationAlgorithms.query(XMOMPersistenceOperationAlgorithms.java:148)
    at com.gip.xyna.xnwh.persistence.xmom.XMOMPersistenceManagement.query(XMOMPersistenceManagement.java:1136)
    at xnwh.persistence.impl.PersistenceServicesServiceOperationImpl.queryExtended(PersistenceServicesServiceOperationImpl.java:103)
    at xnwh.persistence.impl.PersistenceServicesServiceOperationImpl.query(PersistenceServicesServiceOperationImpl.java:96)
    at xnwh.persistence.PersistenceServicesImpl.query(PersistenceServicesImpl.java:127)
    at xnwh.persistence.PersistenceServices.query(PersistenceServices.java:262)
    at xnwh.persistence.Query$Step1.executeInternally(Query.java:211)
    at com.gip.xyna.xprc.xfractwfe.base.FractalProcessStep.execute(FractalProcessStep.java:277)
    at com.gip.xyna.xprc.xfractwfe.base.FractalProcessStep.executeChildren(FractalProcessStep.java:156)
    at xnwh.persistence.Query$Step0.executeInternally(Query.java:155)
    at com.gip.xyna.xprc.xfractwfe.base.FractalProcessStep.execute(FractalProcessStep.java:277)
    at com.gip.xyna.xprc.xfractwfe.base.XynaProcess.executeInternally(XynaProcess.java:190)
    at com.gip.xyna.xprc.xfractwfe.base.XynaProcess.execute(XynaProcess.java:612)
    at com.gip.xyna.xprc.xfractwfe.fractalworkflowexecution.fractalexecution.FractalExecutionProcessor.processInternally(FractalExecutionProcessor.java:162)
    at com.gip.xyna.xprc.xfractwfe.base.AFractalWorkflowProcessor.process(AFractalWorkflowProcessor.java:91)
    at com.gip.xyna.xprc.xpce.execution.ExecutionDispatcher.dispatch(ExecutionDispatcher.java:251)
    at com.gip.xyna.xprc.xpce.execution.XynaExecution.dispatch(XynaExecution.java:54)
    at com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler$1.execute(MasterWorkflowPostScheduler.java:152)
    at com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler.executeAndCatchEverythingExceptSuspension(MasterWorkflowPostScheduler.java:503)
    at com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler$2.execute(MasterWorkflowPostScheduler.java:220)
    at com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler.executeAndCatchEverythingExceptSuspension(MasterWorkflowPostScheduler.java:503)
    at com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler.normalMasterWorkflow(MasterWorkflowPostScheduler.java:772)
    at com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler.runNormal(MasterWorkflowPostScheduler.java:709)
    at com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler.runInternallyWithXynaOrder(MasterWorkflowPostScheduler.java:654)
    at com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler.run(MasterWorkflowPostScheduler.java:583)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
`
(Line numbers correspond to v8.2.11.18, but nothing has changed since.)

I did not find the exact cause even analyzing a heap dump. everything looked fine there.

As an improvement i want to add improved logging for this case and catch the NPE.

**Comment by corneliuslippert-gip** [comment]
The problem was not solved...
