### ISSUE TITLE
MySQLPool socketTimeout won't be set on factory startup

### ISSUE THREAD

**Issue by Moritz-Schrauth-GIP** [Xyna-Factory/xyna-factory#360]
When starting the factory with MySQL PLs, at some point the following error will show up:
```
28-06-2023 12:26:26 XYNA_001  WARN [XynaFactory MAIN] (MySQLPoolType.java:322) - [] Could not adjust socketTimeout for validation. It will not be tried again.
java.lang.NoClassDefFoundError: com/mysql/jdbc/ConnectionImpl
        at com.gip.xyna.xnwh.pools.MySQLPoolType.tryToAdjustSocketTimeout(MySQLPoolType.java:300)
        at com.gip.xyna.xnwh.pools.MySQLPoolType$MySQLValidationStrategy.validate(MySQLPoolType.java:343)
        at com.gip.xyna.utils.db.pool.DefaultRetryStrategy.createConnectionWithRetries(DefaultRetryStrategy.java:53)
        at com.gip.xyna.utils.db.ConnectionPool.createConnectionWithRetries(ConnectionPool.java:199)
        at com.gip.xyna.utils.db.ConnectionPool.<init>(ConnectionPool.java:179)
        at com.gip.xyna.utils.db.ConnectionPool.getInstance(ConnectionPool.java:270)
        at com.gip.xyna.xnwh.pools.ConnectionPoolManagement.startConnectionPool(ConnectionPoolManagement.java:318)
        at com.gip.xyna.xnwh.pools.ConnectionPoolManagement.startAndAddConnectionPool(ConnectionPoolManagement.java:330)
        at com.gip.xyna.xnwh.persistence.mysql.MySQLPersistenceLayer.init(MySQLPersistenceLayer.java:343)
        at com.gip.xyna.xnwh.persistence.PersistenceLayerInstanceBean.createInstance(PersistenceLayerInstanceBean.java:150)
        at com.gip.xyna.xnwh.persistence.ODSImpl.loadFromXMLAndInstantiatePersistenceLayers(ODSImpl.java:1756)
        at com.gip.xyna.xnwh.persistence.ODSImpl$PersistenceLayerInstances.execute(ODSImpl.java:1503)
        at com.gip.xyna.FutureExecution.executeTask(FutureExecution.java:180)
        at com.gip.xyna.FutureExecution.executeTaskList(FutureExecution.java:506)
        at com.gip.xyna.FutureExecution.finishedRegistrationProcess(FutureExecution.java:357)
        at com.gip.xyna.XynaFactory.init(XynaFactory.java:414)
        at com.gip.xyna.xmcp.xfcli.XynaFactoryCommandLineInterface.init(XynaFactoryCommandLineInterface.java:291)
        at com.gip.xyna.xmcp.xfcli.XynaFactoryCommandLineInterface.<init>(XynaFactoryCommandLineInterface.java:129)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.gip.xyna.xmcp.xfcli.XynaFactoryCommandLineInterface.startFactory(XynaFactoryCommandLineInterface.java:584)
        at com.gip.xyna.xmcp.xfcli.XynaFactoryCommandLineInterface.main(XynaFactoryCommandLineInterface.java:499)
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.ConnectionImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 24 more
```

**Comment by Moritz-Schrauth-GIP** [comment]
Was using the wrong jar. On the current version, this doesn't happen
