### ISSUE TITLE
NullPointerException when call clearStatement

### ISSUE THREAD

**Issue by osuender** [Xyna-Factory/xyna-factory#502]
with the code changed in issue 329.

xynautils/database/src/com/gip/xyna/utils/db/SQLUtils
The method clearStatement throws NullPointerException, when the statementCache is used an the resultSet is empty.

at ----- Caused by java.lang.NullPointerException null. (depth: 1) 	at org.mariadb.jdbc.Statement.getMoreResults(Statement.java:818) 	at org.mariadb.jdbc.Statement.getMoreResults(Statement.java:520) 	at com.gip.xyna.utils.db.SQLUtils.clearStatement(SQLUtils.java:560) 	at com.gip.xyna.utils.db.SQLUtils.finallyClose(SQLUtils.java:336)

**Comment by osuender** [comment]
catch NullPointerException in the method clearStatement
